# Generated by Django 4.0.4 on 2022-09-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='manytomany.publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(max_length=100),
        ),
    ]
