# Generated by Django 4.0.4 on 2022-09-06 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_delete_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_unitl',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
